# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g ionic
  displayName: 'install ionic globally'

- script: |
    npm install -g cordova
  displayName: 'install cordova globally'

- script: |
    npm install
  displayName: 'npm install'

# failover for cordova-sqlite-storage error when adding platform
- script: |
    npm i cordova-sqlite-storage@latest
    ionic cordova plugin add cordova-sqlite-storage
  displayName: 'install cordova-sqlite failover'

- script: |
    ionic cordova platform add android
  displayName: 'add android platform'

- script: |
    ionic cordova prepare
  displayName: 'prepare ionic cordova'

- script: |
    ionic cordova build android
  displayName: 'build android'

- script: |
      cd platforms/android/app/build/outputs/apk/debug
      ls -la
  displayName: 'check android build content'

- task: CopyFiles@2
  displayName: 'prepare artifacts for publishing'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      platforms/android/app/build/outputs/apk/debug/app-debug.apk
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1 
  displayName: 'publish artifacts'

#- script: |
#    az storage blob upload --container-name 'public' --file 'platforms/android/app/build/outputs/apk/debug/app-debug.apk' -n 'app-debug.apk' --connection-string 'BlobEndpoint=https://releasestore.blob.core.windows.net/?sv=2018-03-28&ss=bfqt&srt=sco&sp=rwdlacup&se=2019-12-31T00:16:39Z&st=2019-08-12T16:16:39Z&spr=https&sig=diNRRlcHW4x43F9EPV20xHlvG%2FUv2bQnOjJPUcim8EQ%3D'
#  displayName: 'publish to azure storage'

# - task: AppCenterDistribute@3
#   displayName: 'publish to app center'
#   inputs:
#     serverEndpoint: 'App center dist'
#     appSlug: 'tshepo.motsoeneng-palota.co.za/Home-Manager'
#     appFile: 'platforms/android/app/build/outputs/apk/debug/app-debug.apk'
#     symbolsOption: 'Android'
#     releaseNotesOption: 'input'
#     releaseNotesInput: 'Released from Az Devops'
#     destinationType: 'groups'

- task: AppCenterDistribute@3
  displayName: 'publish to app center'
  inputs:
    serverEndpoint: 'App center dist'
    appSlug: 'tshepo.motsoeneng-palota.co.za/Home-Manager'
    appFile: 'platforms/android/app/build/outputs/apk/debug/app-debug.apk'
    symbolsOption: 'Android'
    releaseNotesOption: 'file'
    releaseNotesFile: 'release-notes.txt'
    destinationType: 'groups'



