# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g ionic
  displayName: 'install ionic globally'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    ionic cordova platform add android
  displayName: 'add android platform'

- script: |
    ionic cordova prepare
  displayName: 'prepare ionic cordova'

- script: |
    ionic cordova build android
  displayName: 'build android'

- script: |
      cd platforms/android/app/build/outputs/apk/debug
      dir
  displayName: 'view android build content'
