# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g ionic
  displayName: 'install ionic globally'

- script: |
    npm install -g cordova
  displayName: 'install cordova globally'

- script: |
    npm install
  displayName: 'npm install'

# failover for cordova-sqlite-storage error when adding platform
- script: |
    npm i cordova-sqlite-storage@latest
    ionic cordova plugin add cordova-sqlite-storage
  displayName: 'install cordova-sqlite failover'

- script: |
    ionic cordova platform add android
  displayName: 'add android platform'

- script: |
    ionic cordova prepare
  displayName: 'prepare ionic cordova'

- script: |
    ionic cordova build android
  displayName: 'build android'

- script: |
      cd platforms/android/app/build/outputs/apk/debug
      ls -la
  displayName: 'view android build content'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      platforms/android/app/build/outputs/apk/debug/app-debug.apk
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1 
az storage blob upload \
--container-name "public" \
--file "platforms/android/app/build/outputs/apk/debug/app-debug.apk" \
-n "app-debug.apk" \
--connection-string "BlobEndpoint=https://releasestore.blob.core.windows.net/;QueueEndpoint=https://releasestore.queue.core.windows.net/;FileEndpoint=https://releasestore.file.core.windows.net/;TableEndpoint=https://releasestore.table.core.windows.net/;SharedAccessSignature=sv=2018-03-28&ss=bfqt&srt=sco&sp=rwdlacup&se=2019-08-12T02:22:59Z&st=2019-08-11T18:22:59Z&spr=https&sig=lhe0Lc1D8RYb3gmyqYl%2BoW0PnbbjJed3PcifELdhr3s%3D"